spring.application.name=events

# Usuario do banco
spring.datasource.username = root

# Senha do user
spring.datasource.password = mysql

# URL do banco
spring.datasource.url = jdbc:mysql://localhost:3306/db_events

# Dialeto
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Debug
spring.jpa.show_sql = true